spring:
  application:
    name: admin-service

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info

pet-service:
  base-url: ${PET_SERVICE_BASE_URL:http://localhost:8083}

adoption-service:
  base-url: ${ADOPTION_SERVICE_BASE_URL:http://localhost:8084}
